export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ORDERBYPRICE = "ORDERBYPRICE";
export const FILTERBYMUEBLES = "FILTERBYMUEBLES";
export const GET_DETAIL = "GET_DETAIL";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const FILTER_BY_CATEGORIES = "FILTER_BY_CATEGORIES";
export const FILTER_BY_COLOR = "FILTER_BY_COLOR";
export const GET_BY_HASHTAG = "GET_BY_HASHTAG";
export const GET_BY_NAME = "GET_BY_NAME";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const FILTER_RESTART = 'FILTER_RESTART';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const FILTER_BY_MATERIAL = "FILTER_BY_MATERIAL";
export const GET_DESING = "GET_DESING";


