export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ORDERBYPRICE = "ORDERBYPRICE";
export const FILTERBYCOLOR = "FILTERBYCOLOR";
export const FILTERBYMUEBLES= "FILTERBYMUEBLES";
export const GET_DETAIL = "GET_DETAIL";
export const CLEAR_DETAIL = "CLEAR_DETAIL";


